name: doctro
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.7+14

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  agora_rtc_engine: ^4.0.7
  auto_size_text: ^3.0.0-nullsafety.0
  barcode_widget: ^2.0.1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  connectivity: ^3.0.6
  country_picker: ^2.0.7
  cupertino_icons: ^1.0.3
  dotted_line: ^3.0.0
  file_picker: ^4.0.0
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_credit_card: ^3.0.1
  flutter_custom_clippers: ^2.0.0
  flutter_facebook_auth: ^4.1.2
  flutter_google_places: ^0.3.0
  flutter_html: ^3.0.0-alpha.1
  flutter_launcher_icons: ^0.9.0
  flutter_localizations:
    sdk: flutter
  flutter_paystack: ^1.0.5+1
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.1.0
  flutter_stripe:
  firebase_messaging:
  flutter_svg: ^1.0.0
  fluttertoast: ^8.0.8
  flutterwave: ^1.0.1
  font_awesome_flutter: ^10.1.0
  form_field_validator: ^1.1.0
  geolocator: ^8.0.1
  google_api_headers: ^1.0.0
  google_maps_flutter: ^2.0.11
  google_maps_webservice: ^0.0.20-nullsafety.2
  google_sign_in:
  html: ^0.15.0
  http: ^0.13.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  json_annotation: ^4.0.0
  location: ^4.3.0
  logger: ^1.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  otp_text_field: ^1.1.0
  path_provider: any
  permission_handler: ^9.2.0
  pinput: ^1.2.0
  pip_view: ^0.9.6-nullsafety
  progress_indicators: ^1.0.0
  provider: ^6.0.2
  razorpay_flutter: ^1.2.9
  retrofit: any
  shared_preferences: ^2.0.6
  sqflite: any
  url_launcher: ^6.0.9
  uuid: ^3.0.5
  onesignal_flutter: ^3.3.0
  in_app_update: ^3.0.0
  firebase_core_platform_interface: 4.5.1
  change_app_package_name: ^1.1.0

dev_dependencies:
  build_runner: any
#  flutter_native_splash: ^1.1.8+4
  flutter_test:
    sdk: flutter
  retrofit_generator: any

#flutter_native_splash:
#  color: "#FFFFFF"
#  image: assets/images/splash.png
#  color_dark: "#1a1a1a"
#  image_dark: assets/images/splash.png
#  android: true
#  ios: true
#  android_gravity: center
#  ios_content_mode: center

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - lib/localization/languages/
