// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw3_doaHHE790SExZW6UP6dlO9oZLitB0',
    appId: '1:108088647271:android:27a94b779c34d3e70afec2',
    messagingSenderId: '108088647271',
    projectId: 'famous-gearing-333512',
    storageBucket: 'famous-gearing-333512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn8ZlOda9TC9-AdJ9gnW7530Hxd0yxpXI',
    appId: '1:108088647271:ios:ed8cfe92bd46ba7f0afec2',
    messagingSenderId: '108088647271',
    projectId: 'famous-gearing-333512',
    storageBucket: 'famous-gearing-333512.appspot.com',
    androidClientId: '108088647271-1v12k646cg1ha1heimudjpp8d56em89u.apps.googleusercontent.com',
    iosClientId: '108088647271-kdvd4un1h2pbo09pn7tingv2j7jkbpac.apps.googleusercontent.com',
    iosBundleId: 'com.cat.dakatra.patient',
  );
}
